const state={tools:[],view:'all',category:'',query:'',type:'',sort:'name',settings:{theme:'system',density:'comfortable'}};
const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);

async function load(){
  const r=await chrome.storage.local.get(['tools','settings']);
  state.tools=(Array.isArray(r.tools)?r.tools:[]).map(x=>({...x,id:x.id||uid(),tags:Array.isArray(x.tags)?x.tags:[],favorite:Boolean(x.favorite),lastUsed:Number(x.lastUsed||0),addedAt:Number(x.addedAt||0)}));
  state.settings={...state.settings,...(r.settings||{})};
  await chrome.storage.local.set({tools:state.tools,settings:state.settings});
  applySettings();render();
}
async function save(){await chrome.storage.local.set({tools:state.tools,settings:state.settings});}
function applySettings(){const dark=state.settings.theme==='dark'||(state.settings.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',dark);$('grid').classList.toggle('compact',state.settings.density==='compact');$('theme').value=state.settings.theme;$('density').value=state.settings.density}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}
function hostname(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return ''}}
function favicon(url){const h=hostname(url);return h?`https://www.google.com/s2/favicons?domain=${encodeURIComponent(h)}&sz=64`:''}
function categories(){return [...new Set(state.tools.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function renderSidebar(){const cats=categories();$('category-list').innerHTML=cats.map(c=>`<button class="category-item ${state.category===c?'selected':''}" data-cat="${esc(c)}"><span>${esc(c)}</span><b>${state.tools.filter(x=>x.category===c).length}</b></button>`).join('');$('count-all').textContent=state.tools.length;$('count-fav').textContent=state.tools.filter(x=>x.favorite).length;$('count-recent').textContent=state.tools.filter(x=>x.lastUsed).length}
function filtered(){let arr=[...state.tools];if(state.view==='favorites')arr=arr.filter(x=>x.favorite);if(state.view==='recent')arr=arr.filter(x=>x.lastUsed);if(state.category)arr=arr.filter(x=>x.category===state.category);if(state.type)arr=arr.filter(x=>x.type===state.type);const q=state.query.toLowerCase().trim();if(q)arr=arr.filter(x=>[x.name,x.url,x.category,x.description,x.notes,(x.tags||[]).join(' ')].join(' ').toLowerCase().includes(q));if(state.sort==='name')arr.sort((a,b)=>a.name.localeCompare(b.name));if(state.sort==='category')arr.sort((a,b)=>(a.category||'').localeCompare(b.category||'')||a.name.localeCompare(b.name));if(state.sort==='recent')arr.sort((a,b)=>(b.lastUsed||0)-(a.lastUsed||0));if(state.sort==='added')arr.sort((a,b)=>(b.addedAt||0)-(a.addedAt||0));return arr}
function render(){
  renderSidebar();const arr=filtered();
  $('view-title').textContent=state.category||({all:'All Tools',favorites:'Favorites',recent:'Recently Used'}[state.view]||'All Tools');
  $('view-count').textContent=`${arr.length} tool${arr.length===1?'':'s'}`;
  $('grid').innerHTML=arr.map(card).join('');$('empty').classList.toggle('hidden',arr.length>0);
  $('stat-tools').textContent=state.tools.length;$('stat-categories').textContent=categories().length;$('stat-favorites').textContent=state.tools.filter(x=>x.favorite).length;$('stat-recent').textContent=state.tools.filter(x=>x.lastUsed).length;
  document.querySelectorAll('.star').forEach(b=>b.onclick=()=>toggleFav(b.dataset.id));
  document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openTool(b.dataset.open));
  document.querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>showDetails(b.dataset.details));
  document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleCardMenu(b.dataset.menu,b)});
  document.querySelectorAll('[data-menu-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();handleMenuAction(b.dataset.menuAction,b.dataset.id)});
  document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;state.view='all';setActiveNav('all');render()});
}
function card(x){const tags=(x.tags||[]).slice(0,3).map(t=>`<span class="chip">${esc(t)}</span>`).join('');const icon=favicon(x.url);return `<article class="card" data-card="${esc(x.id)}"><div class="card-top"><div class="favicon">${icon?`<img src="${icon}" alt="" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:''}<span class="fallback">${esc((x.name||'?').slice(0,1).toUpperCase())}</span></div><div class="card-title">${esc(x.name)}<div class="card-title-sub">${esc(hostname(x.url))}</div></div><button class="star ${x.favorite?'on':''}" data-id="${esc(x.id)}" title="${x.favorite?'Remove favorite':'Add favorite'}">★</button></div><div class="desc">${esc(x.description||'')}</div><div class="chips"><span class="chip category-chip">${esc(x.category||'Uncategorized')}</span>${tags}</div><div class="card-actions"><button class="btn primary" data-open="${esc(x.id)}">Open ↗</button><button class="btn" data-details="${esc(x.id)}">Details</button><button class="btn menu-btn" data-menu="${esc(x.id)}" title="More actions">⋮</button></div><div class="card-menu hidden" data-menu-box="${esc(x.id)}"><button data-menu-action="details" data-id="${esc(x.id)}">◉ View Details</button><button data-menu-action="edit" data-id="${esc(x.id)}">✎ Edit / Update</button><button data-menu-action="favorite" data-id="${esc(x.id)}">★ ${x.favorite?'Remove Favorite':'Add to Favorites'}</button><button data-menu-action="open" data-id="${esc(x.id)}">↗ Open Tool</button><button class="danger-item" data-menu-action="delete" data-id="${esc(x.id)}">⌫ Delete</button></div></article>`}

function toggleCardMenu(id){document.querySelectorAll('.card-menu').forEach(m=>m.classList.toggle('hidden',m.dataset.menuBox!==id||!m.classList.contains('hidden')));}
function closeCardMenus(){document.querySelectorAll('.card-menu').forEach(m=>m.classList.add('hidden'));}
async function handleMenuAction(action,id){closeCardMenus();if(action==='details')return showDetails(id);if(action==='edit')return editTool(id);if(action==='open')return openTool(id);if(action==='favorite')return toggleFav(id);if(action==='delete'){const x=state.tools.find(t=>t.id===id);if(!x)return;if(confirm(`Delete "${x.name}"?`)){state.tools=state.tools.filter(t=>t.id!==id);await save();render();toast('Tool deleted')}}}
document.addEventListener('click',e=>{if(!e.target.closest('.card-menu')&&!e.target.closest('[data-menu]'))closeCardMenus()});
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function openTool(id){
  const x=state.tools.find(t=>t.id===id);if(!x)return toast('Tool not found');
  let url=String(x.url||'').trim();if(!url)return toast('This tool has no URL');if(!/^https?:\/\//i.test(url))url='https://'+url;
  try{await chrome.tabs.create({url});x.lastUsed=Date.now();await save();render();toast('Opened '+x.name)}catch(err){try{window.open(url,'_blank','noopener,noreferrer');x.lastUsed=Date.now();await save();render();}catch{toast('Could not open tool')}}
}
function showDetails(id){const x=state.tools.find(t=>t.id===id);if(!x)return toast('Tool not found');$('details-title').textContent=x.name||'Tool Details';const f=favicon(x.url);$('details-favicon').src=f||'';$('details-favicon').style.display=f?'block':'none';$('details-fallback').style.display=f?'none':'grid';$('details-fallback').textContent=(x.name||'?').slice(0,1).toUpperCase();$('details-name').textContent=x.name||'Untitled';$('details-url').textContent=x.url||'—';$('details-url').href=x.url||'#';$('details-url-code').textContent=x.url||'—';$('details-category').textContent=x.category||'Uncategorized';$('details-type').textContent=x.type||'Website';$('details-description').textContent=x.description||'No description added.';$('details-notes').textContent=x.notes||'No personal notes added.';$('details-tags').innerHTML=(x.tags||[]).length?(x.tags||[]).map(t=>`<span class="chip">${esc(t)}</span>`).join(''):'<span class="muted">No tags</span>';$('details-open').onclick=()=>{closeDetails();openTool(x.id)};$('details-edit').onclick=()=>{closeDetails();editTool(x.id)};$('details-delete').onclick=async()=>{if(confirm(`Delete "${x.name}"?`)){state.tools=state.tools.filter(t=>t.id!==x.id);await save();closeDetails();render();toast('Tool deleted')}};$('details-favorite').textContent=x.favorite?'★ Remove Favorite':'★ Add to Favorites';$('details-favorite').onclick=async()=>{await toggleFav(x.id);showDetails(x.id)};$('details-modal').classList.remove('hidden')}
function closeDetails(){$('details-modal').classList.add('hidden')}
async function toggleFav(id){const x=state.tools.find(t=>t.id===id);if(!x)return;x.favorite=!x.favorite;await save();render()}
function openModal(tool=null){$('modal').classList.remove('hidden');$('modal-title').textContent=tool?'Edit / Update Tool':'Add Tool';$('tool-id').value=tool?.id||'';$('tool-name').value=tool?.name||'';$('tool-url').value=tool?.url||'';$('tool-category').value=tool?.category||'';$('tool-type').value=tool?.type||'Website';$('tool-tags').value=(tool?.tags||[]).join(', ');$('tool-description').value=tool?.description||'';$('tool-notes').value=tool?.notes||'';$('delete-tool').classList.toggle('hidden',!tool)}
function closeModal(){$('modal').classList.add('hidden')}
function editTool(id){const x=state.tools.find(x=>x.id===id);if(x)openModal(x)}
$('tool-form').onsubmit=async e=>{e.preventDefault();const id=$('tool-id').value||uid();const old=state.tools.find(x=>x.id===id);let url=$('tool-url').value.trim();if(url&&!/^https?:\/\//i.test(url))url='https://'+url;const item={id,name:$('tool-name').value.trim(),url,category:$('tool-category').value.trim()||'Uncategorized',type:$('tool-type').value,tags:$('tool-tags').value.split(',').map(x=>x.trim()).filter(Boolean),description:$('tool-description').value.trim(),notes:$('tool-notes').value.trim(),favorite:old?.favorite||false,lastUsed:old?.lastUsed||0,addedAt:old?.addedAt||Date.now()};if(!/^https?:\/\//i.test(item.url))return toast('Use a valid http/https URL');const dup=state.tools.find(x=>normalizeUrl(x.url)===normalizeUrl(item.url)&&x.id!==id);if(dup)return toast('A tool with this URL already exists');if(old)Object.assign(old,item);else state.tools.push(item);await save();closeModal();render();toast(old?'Tool updated':'Tool added')}
$('delete-tool').onclick=async()=>{const id=$('tool-id').value;if(!id)return;const x=state.tools.find(t=>t.id===id);if(!confirm(`Delete "${x?.name||'this tool'}"?`))return;state.tools=state.tools.filter(x=>x.id!==id);await save();closeModal();render();toast('Tool deleted')};
$('open-add').onclick=()=>openModal();$('sidebar-add').onclick=()=>openModal();$('close-modal').onclick=closeModal;$('close-details').onclick=closeDetails;$('cancel-modal').onclick=closeModal;$('settings-btn').onclick=()=>{$('settings-modal').classList.remove('hidden')};$('close-settings').onclick=()=>{$('settings-modal').classList.add('hidden')};
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));
$('search').oninput=e=>{state.query=e.target.value;render()};$('type-filter').onchange=e=>{state.type=e.target.value;render()};$('sort').onchange=e=>{state.sort=e.target.value;render()};$('clear-search').onclick=()=>{state.query='';state.type='';state.category='';state.view='all';$('search').value='';$('type-filter').value='';setActiveNav('all');render()};
function setActiveNav(view){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view))}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.category='';setActiveNav(state.view);render()});
$('theme').onchange=async e=>{state.settings.theme=e.target.value;await save();applySettings()};$('density').onchange=async e=>{state.settings.density=e.target.value;await save();applySettings()};
$('export-json').onclick=()=>{const payload={version:2,app:'Charlie MJ Tool Archive',exportedAt:new Date().toISOString(),tools:state.tools};download('charlie-mj-tools.json',JSON.stringify(payload,null,2),'application/json');toast('JSON backup exported')};
$('export-csv').onclick=()=>{const rows=[['Name','URL','Category','Type','Tags','Description','Notes','Favorite','Last Used']];for(const x of state.tools)rows.push([x.name,x.url,x.category,x.type,(x.tags||[]).join('; '),x.description||'',x.notes||'',x.favorite?'Yes':'No',x.lastUsed?new Date(x.lastUsed).toISOString():'']);const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');download('charlie-mj-tools.csv',csv,'text/csv');toast('CSV exported')};
$('import-json').onclick=()=>$('json-file').click();$('json-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());const incoming=Array.isArray(data)?data:data.tools;if(!Array.isArray(incoming))throw Error('Invalid format');const before=state.tools.length;state.tools=mergeTools(incoming);await save();render();toast(`Added ${state.tools.length-before} new tools`)}catch(err){toast('Invalid JSON file')}e.target.value=''};
$('import-html').onclick=()=>$('html-file').click();$('html-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const html=await f.text();const incoming=parseBookmarks(html);const before=state.tools.length;state.tools=mergeTools(incoming);await save();render();toast(`Added ${state.tools.length-before} new bookmarks`)}catch(err){toast('Could not read bookmarks HTML')}e.target.value=''};
$('restore-defaults').onclick=async()=>{try{const r=await fetch('../data/default-tools.json');const incoming=await r.json();const before=state.tools.length;state.tools=mergeTools(incoming);await save();render();toast(`Default library restored: ${state.tools.length-before} new tools`)}catch{toast('Could not restore default library')}};
$('open-visible').onclick=async()=>{const arr=filtered();if(!arr.length)return toast('No visible tools to open');if(arr.length>15&&!confirm(`Open ${arr.length} tabs?`))return;for(const x of arr){let url=x.url;if(!/^https?:\/\//i.test(url))url='https://'+url;try{await chrome.tabs.create({url,active:false});x.lastUsed=Date.now()}catch{}}await save();render();toast(`Opened ${arr.length} tabs`)};
function mergeTools(incoming){const byUrl=new Map(state.tools.map(x=>[normalizeUrl(x.url),x]));for(const x of incoming){if(!x?.url)continue;const key=normalizeUrl(x.url);if(!byUrl.has(key)){const n={id:x.id||uid(),name:x.name||'Untitled',url:x.url,category:x.category||'Imported',type:x.type||'Website',tags:Array.isArray(x.tags)?x.tags:[],description:x.description||'',notes:x.notes||'',favorite:false,lastUsed:0,addedAt:Date.now()};state.tools.push(n);byUrl.set(key,n)}}return state.tools}
function normalizeUrl(u){try{const x=new URL(u);x.hash='';return x.toString().replace(/\/$/,'').toLowerCase()}catch{return String(u).trim().toLowerCase().replace(/\/$/,'')}}
function parseBookmarks(html){const doc=new DOMParser().parseFromString(html,'text/html');const out=[];const links=doc.querySelectorAll('a[href]');links.forEach(a=>{const url=a.getAttribute('href');if(!/^https?:/i.test(url))return;let p=a.parentElement;let folder='Imported Bookmarks';while(p){const h=p.previousElementSibling;if(h&&h.tagName==='H3'){folder=h.textContent.trim();break}p=p.parentElement}out.push({name:a.textContent.trim()||url,url,category:folder,type:'Website',tags:[]})});return out}
function download(name,text,type){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('search').focus()}if(e.key==='Escape'){closeModal();closeDetails();$('settings-modal').classList.add('hidden');closeCardMenus()}});
load();
