const state = {
  tools: [], view: 'all', category: '', query: '', type: '', sort: 'name',
  selected: new Set(), settings: { theme: 'system', density: 'comfortable' }, pendingImport: null
};
const $ = id => document.getElementById(id);
const uid = () => crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36) + Math.random().toString(36).slice(2);

function esc(s = '') { return String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function hostname(url) { try { return new URL(url).hostname.replace(/^www\./,''); } catch { return ''; } }
function favicon(url) { const h = hostname(url); return h ? `https://www.google.com/s2/favicons?domain=${encodeURIComponent(h)}&sz=64` : ''; }
function normalizeUrl(url) {
  try {
    const u = new URL(String(url || '').trim());
    // Query-string variants of the same saved page count as one archive website.
    u.search = ''; u.hash = ''; u.protocol = u.protocol.toLowerCase();
    u.hostname = u.hostname.toLowerCase().replace(/^www\./,'');
    u.pathname = u.pathname.replace(/\/{2,}/g,'/').replace(/\/$/,'') || '/';
    return u.toString().replace(/\/$/,'').toLowerCase();
  } catch { return String(url || '').trim().toLowerCase().replace(/\/$/,''); }
}
function tokenise(s='') { return String(s).toLowerCase().replace(/[^a-z0-9\s-]/g,' ').split(/\s+/).filter(w => w.length > 2); }
function unique(arr) { return [...new Set(arr.filter(Boolean))]; }
function categories() { return unique(state.tools.map(x => x.category || 'Uncategorized')).sort((a,b)=>a.localeCompare(b)); }
function normalizeTool(raw, source='local') {
  return { id: raw.id || uid(), name: String(raw.name || 'Untitled').trim(), url: String(raw.url || '').trim(), category: String(raw.category || 'Uncategorized').trim() || 'Uncategorized', type: String(raw.type || 'Website'), tags: Array.isArray(raw.tags) ? unique(raw.tags.map(String).map(x=>x.trim())) : [], description: String(raw.description || '').trim(), notes: String(raw.notes || '').trim(), favorite: Boolean(raw.favorite), lastUsed: Number(raw.lastUsed || 0), addedAt: Number(raw.addedAt || Date.now()), lastModified: Number(raw.lastModified || raw.addedAt || Date.now()), source: raw.source || source, githubSyncedAt: Number(raw.githubSyncedAt || 0) };
}

const detailHints = {
  'downloadfury': 'PC games resource page focused on finding and browsing PC game downloads.',
  'filecr': 'Software download resource for browsing desktop applications and related files.',
  'hisgames': 'PC gaming resource for discovering and browsing game-related downloads.',
  'gamingbeasts': 'PC gaming resource covering games and game-related downloads.',
  'steamunlocked': 'PC gaming resource focused on browsing downloadable game titles.',
  'ipcgames': 'PC gaming resource for discovering PC game titles and related downloads.',
  'oceanoffgames': 'PC gaming resource for discovering game titles and downloadable content.',
  'designweek': 'Design and creative-industry publication covering design news, trends and professional insights.',
  'graphicdesignforum': 'Community discussion forum for graphic design topics, questions and creative resources.',
  'positivepsychology': 'Psychology resource with practical articles and worksheets for personal development and wellbeing topics.',
  'headline-analyzer': 'Headline analysis tool for reviewing and improving titles used in content and marketing.',
  'titlecaseconverter.': 'Online text utility for converting titles and headings into title case.',
  'convertcase': 'Online text utility for changing capitalization and letter case.',
  'capitalizemytitle': 'Title formatting utility for creating and checking capitalization in headings.',
  'content-analysis': 'Content analysis resource for reviewing readability, SEO and content quality signals.',
  'worldmags': 'Online magazine resource for browsing magazine titles and publication-related content.',
  'speedtest': 'Network testing utility for measuring internet connection speed and performance.',
  'Fast Speed Tester': 'Simple internet speed testing service for checking download and connection performance.',
  'printwhatyoulike': 'Web printing utility designed to simplify pages before printing or saving them.'
};
function enrichTool(x) {
  const key = String(x.name || '').trim();
  if (!x.description) x.description = detailHints[key] || `${x.category || 'Online'} resource: ${x.name}. Useful for quick access from your personal tool archive.`;
  if (!Array.isArray(x.tags)) x.tags=[];
  if (!x.tags.length) x.tags = unique([...tokenise(x.name).slice(0,3), ...tokenise(x.category).slice(0,2)]);
  return x;
}
function dedupeTools(input) {
  const byUrl = new Map(), out=[]; let removed=0;
  for (const raw of input || []) {
    const x = enrichTool(normalizeTool(raw)); const key=normalizeUrl(x.url);
    if (!key) continue;
    const old=byUrl.get(key);
    if (!old) { byUrl.set(key,x); out.push(x); continue; }
    removed++;
    old.tags=unique([...(old.tags||[]),...(x.tags||[])]);
    if ((!old.description || old.description.includes('Useful for quick access')) && x.description && !x.description.includes('Useful for quick access')) old.description=x.description;
    if (!old.notes && x.notes) old.notes=x.notes;
    if (x.favorite) old.favorite=true;
    old.lastUsed=Math.max(old.lastUsed||0,x.lastUsed||0); old.addedAt=Math.min(old.addedAt||Date.now(),x.addedAt||Date.now());
  }
  return {tools:out,removed};
}
async function save(){ await chrome.storage.local.set({tools:state.tools,settings:state.settings}); }
function toast(msg){ const t=$('toast'); t.textContent=msg; t.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>t.classList.remove('show'),3000); }
function applySettings(){ const dark=state.settings.theme==='dark'||(state.settings.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches); document.body.classList.toggle('dark',dark); $('grid').classList.toggle('compact',state.settings.density==='compact'); $('theme').value=state.settings.theme; $('density').value=state.settings.density; }

async function load(){
  const r=await chrome.storage.local.get(['tools','settings']);
  const cleaned=dedupeTools(Array.isArray(r.tools)?r.tools:[]); state.tools=cleaned.tools; state.settings={...state.settings,...(r.settings||{})};
  await save(); applySettings(); render();
  setTimeout(syncGithub,700);
}
async function syncGithub(){
  try { const result=await chrome.runtime.sendMessage({type:'sync-github'}); if(result?.ok){ await refreshFromStorage(); toast(result.added?`GitHub sync: ${result.added} new tool${result.added===1?'':'s'} added`:'GitHub sync complete'); } else if(result?.error) toast('GitHub sync: '+result.error); } catch { toast('GitHub sync could not start'); }
}
async function refreshFromStorage(){ const r=await chrome.storage.local.get(['tools','settings']); const cleaned=dedupeTools(Array.isArray(r.tools)?r.tools:[]); state.tools=cleaned.tools; state.settings={...state.settings,...(r.settings||{})}; await save(); render(); }

function renderSidebar(){ const cats=categories(); $('category-list').innerHTML=cats.map(c=>`<button class="category-item ${state.category===c?'selected':''}" data-cat="${esc(c)}"><span>${esc(c)}</span><b>${state.tools.filter(x=>x.category===c).length}</b></button>`).join(''); $('count-all').textContent=state.tools.length; $('count-fav').textContent=state.tools.filter(x=>x.favorite).length; $('count-recent').textContent=state.tools.filter(x=>x.lastUsed).length; }
function parseSearch(q){ const out={text:[],category:null,tag:null,favorite:null,type:null,recent:false}; const re=/(?:^|\s)(category|tag|favorite|type|used):("[^"]+"|\S+)/gi; let m,last=0; while((m=re.exec(q))){ out[m[1].toLowerCase()] = m[2].replace(/^"|"$/g,''); last=re.lastIndex; } const stripped=q.replace(re,' ').trim(); out.text=stripped.split(/\s+/).filter(Boolean); out.recent=String(out.used||'').toLowerCase()==='recent'; return out; }
function filtered(){
  let arr=[...state.tools]; if(state.view==='favorites') arr=arr.filter(x=>x.favorite); if(state.view==='recent') arr=arr.filter(x=>x.lastUsed); if(state.category) arr=arr.filter(x=>x.category===state.category); if(state.type) arr=arr.filter(x=>x.type===state.type);
  const p=parseSearch(state.query.toLowerCase()); if(p.category) arr=arr.filter(x=>(x.category||'').toLowerCase().includes(p.category.toLowerCase())); if(p.tag) arr=arr.filter(x=>(x.tags||[]).some(t=>t.toLowerCase().includes(p.tag.toLowerCase()))); if(p.favorite) arr=arr.filter(x=>String(x.favorite)===String(p.favorite).toLowerCase()); if(p.type) arr=arr.filter(x=>(x.type||'').toLowerCase()===p.type.toLowerCase()); if(p.recent) arr=arr.filter(x=>x.lastUsed); if(p.text.length) arr=arr.filter(x=>p.text.every(q=>[x.name,x.url,x.category,x.description,x.notes,(x.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)));
  if(state.sort==='name') arr.sort((a,b)=>a.name.localeCompare(b.name)); if(state.sort==='category') arr.sort((a,b)=>(a.category||'').localeCompare(b.category||'')||a.name.localeCompare(b.name)); if(state.sort==='recent') arr.sort((a,b)=>(b.lastUsed||0)-(a.lastUsed||0)); if(state.sort==='added') arr.sort((a,b)=>(b.addedAt||0)-(a.addedAt||0)); return arr;
}
function card(x){ const tags=(x.tags||[]).slice(0,3).map(t=>`<span class="chip">${esc(t)}</span>`).join(''); const icon=favicon(x.url); const selected=state.selected.has(x.id); return `<article class="card ${selected?'selected':''}" data-card="${esc(x.id)}"><input class="card-select" type="checkbox" data-select="${esc(x.id)}" ${selected?'checked':''} title="Select tool"><div class="card-top" style="padding-left:18px"><div class="favicon">${icon?`<img src="${icon}" alt="" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:''}<span class="fallback">${esc((x.name||'?').slice(0,1).toUpperCase())}</span></div><div class="card-title">${esc(x.name)}<div class="card-title-sub">${esc(hostname(x.url))}</div></div><button class="star ${x.favorite?'on':''}" data-id="${esc(x.id)}" title="${x.favorite?'Remove favorite':'Add favorite'}">★</button></div><div class="desc">${esc(x.description||'')}</div><div class="chips"><span class="chip category-chip">${esc(x.category||'Uncategorized')}</span>${tags}</div><div class="card-actions"><button class="btn primary" data-open="${esc(x.id)}">Open ↗</button><button class="btn" data-details="${esc(x.id)}">Details</button><button class="btn menu-btn" data-menu="${esc(x.id)}" title="More actions">⋮</button></div><div class="card-menu hidden" data-menu-box="${esc(x.id)}"><button data-menu-action="details" data-id="${esc(x.id)}">◉ View Details</button><button data-menu-action="edit" data-id="${esc(x.id)}">✎ Edit / Update</button><button data-menu-action="favorite" data-id="${esc(x.id)}">★ ${x.favorite?'Remove Favorite':'Add to Favorites'}</button><button data-menu-action="category" data-id="${esc(x.id)}">▣ Move Category</button><button data-menu-action="open" data-id="${esc(x.id)}">↗ Open Tool</button><button class="danger-item" data-menu-action="delete" data-id="${esc(x.id)}">⌫ Delete</button></div></article>`; }
function render(){ renderSidebar(); const arr=filtered(); $('view-title').textContent=state.category||({all:'All Tools',favorites:'Favorites',recent:'Recently Used'}[state.view]||'All Tools'); $('view-count').textContent=`${arr.length} tool${arr.length===1?'':'s'}`; $('grid').innerHTML=arr.map(card).join(''); $('empty').classList.toggle('hidden',arr.length>0); $('stat-tools').textContent=state.tools.length; $('stat-categories').textContent=categories().length; $('stat-favorites').textContent=state.tools.filter(x=>x.favorite).length; $('stat-recent').textContent=state.tools.filter(x=>x.lastUsed).length; $('bulkbar').classList.toggle('hidden',state.selected.size===0); $('selected-count').textContent=state.selected.size;
  document.querySelectorAll('.star').forEach(b=>b.onclick=()=>toggleFav(b.dataset.id)); document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openTool(b.dataset.open)); document.querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>showDetails(b.dataset.details)); document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleCardMenu(b.dataset.menu)}); document.querySelectorAll('[data-menu-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();handleMenuAction(b.dataset.menuAction,b.dataset.id)}); document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;state.view='all';setActiveNav('all');render()}); document.querySelectorAll('[data-select]').forEach(b=>b.onchange=()=>{if(b.checked)state.selected.add(b.dataset.select);else state.selected.delete(b.dataset.select);render()}); }
function toggleCardMenu(id){document.querySelectorAll('.card-menu').forEach(m=>m.classList.toggle('hidden',m.dataset.menuBox!==id||!m.classList.contains('hidden')))} function closeCardMenus(){document.querySelectorAll('.card-menu').forEach(m=>m.classList.add('hidden'))}
async function handleMenuAction(action,id){closeCardMenus(); if(action==='details')return showDetails(id); if(action==='edit')return editTool(id); if(action==='open')return openTool(id); if(action==='favorite')return toggleFav(id); if(action==='category')return moveTools([id]); if(action==='delete'){const x=state.tools.find(t=>t.id===id);if(x&&confirm(`Delete "${x.name}"?`)){state.tools=state.tools.filter(t=>t.id!==id);await save();render();toast('Tool deleted')}}}
document.addEventListener('click',e=>{if(!e.target.closest('.card-menu')&&!e.target.closest('[data-menu]'))closeCardMenus()});

async function openTool(id){const x=state.tools.find(t=>t.id===id);if(!x)return toast('Tool not found');let url=String(x.url||'').trim();if(!url)return toast('This tool has no URL');if(!/^https?:\/\//i.test(url))url='https://'+url;try{await chrome.tabs.create({url});x.lastUsed=Date.now();x.usageCount=Number(x.usageCount||0)+1;x.lastModified=Date.now();await save();render();toast('Opened '+x.name)}catch{toast('Could not open tool')}}
function showDetails(id){const x=state.tools.find(t=>t.id===id);if(!x)return toast('Tool not found');$('details-title').textContent=x.name||'Tool Details';const f=favicon(x.url);$('details-favicon').src=f||'';$('details-favicon').style.display=f?'block':'none';$('details-fallback').style.display=f?'none':'grid';$('details-fallback').textContent=(x.name||'?').slice(0,1).toUpperCase();$('details-name').textContent=x.name||'Untitled';$('details-url').textContent=x.url||'—';$('details-url').href=x.url||'#';$('details-url-code').textContent=x.url||'—';$('details-category').textContent=x.category||'Uncategorized';$('details-type').textContent=x.type||'Website';$('details-description').textContent=x.description||'No description added.';$('details-notes').textContent=x.notes||'No personal notes added.';$('details-tags').innerHTML=(x.tags||[]).length?x.tags.map(t=>`<span class="chip">${esc(t)}</span>`).join(''):'<span class="muted">No tags</span>';$('details-usage').textContent=x.lastUsed?`Opened ${x.lastUsed?new Date(x.lastUsed).toLocaleString():'—'}${x.usageCount?` · ${x.usageCount} recorded opens`:''}`:'Not opened yet';$('details-open').onclick=()=>{closeDetails();openTool(x.id)};$('details-edit').onclick=()=>{closeDetails();editTool(x.id)};$('details-delete').onclick=async()=>{if(confirm(`Delete "${x.name}"?`)){state.tools=state.tools.filter(t=>t.id!==x.id);await save();closeDetails();render();toast('Tool deleted')}};$('details-favorite').textContent=x.favorite?'★ Remove Favorite':'★ Add to Favorites';$('details-favorite').onclick=async()=>{await toggleFav(x.id);showDetails(x.id)};$('details-modal').classList.remove('hidden')}
function closeDetails(){$('details-modal').classList.add('hidden')}
async function toggleFav(id){const x=state.tools.find(t=>t.id===id);if(!x)return;x.favorite=!x.favorite;x.lastModified=Date.now();await save();render()}

function openModal(tool=null){$('modal').classList.remove('hidden');$('modal-title').textContent=tool?'Edit / Update Tool':'Add Tool';$('tool-id').value=tool?.id||'';$('tool-name').value=tool?.name||'';$('tool-url').value=tool?.url||'';$('tool-category').value=tool?.category||'';$('tool-type').value=tool?.type||'Website';$('tool-tags').value=(tool?.tags||[]).join(', ');$('tool-description').value=tool?.description||'';$('tool-notes').value=tool?.notes||'';$('delete-tool').classList.toggle('hidden',!tool);$('duplicate-box').classList.add('hidden');$('similar-box').classList.add('hidden');renderCategorySuggestions();renderTagSuggestions();}
function closeModal(){$('modal').classList.add('hidden');$('category-suggestions').classList.add('hidden')}
function editTool(id){const x=state.tools.find(x=>x.id===id);if(x)openModal(x)}
function duplicateForUrl(url,ignoreId=''){const key=normalizeUrl(url);return state.tools.find(x=>x.id!==ignoreId&&key&&normalizeUrl(x.url)===key)}
function showUrlWarnings(){const url=$('tool-url').value.trim(), id=$('tool-id').value; const dup=duplicateForUrl(url,id); if(dup){$('duplicate-box').innerHTML=`<div class="warning-box">⚠️ <strong>Website already exists.</strong> ${esc(dup.name)} · ${esc(dup.category)} <button type="button" class="btn" style="margin-left:6px" onclick="document.getElementById('modal').classList.add('hidden');showDetails('${esc(dup.id)}')">View Existing</button></div>`;$('duplicate-box').classList.remove('hidden')}else $('duplicate-box').classList.add('hidden');
  const parts=tokenise(($('tool-name').value+' '+url+' '+$('tool-category').value)); const similar=state.tools.filter(x=>x.id!==id).map(x=>({x,score:unique([...tokenise(x.name),...tokenise(x.url)]).filter(t=>parts.includes(t)).length})).filter(o=>o.score>=2).sort((a,b)=>b.score-a.score).slice(0,4); if(similar.length){$('similar-box').innerHTML=`<div class="success-box">🔎 <strong>Similar tools already exist.</strong><ul class="similar-list">${similar.map(o=>`<li>${esc(o.x.name)} · ${esc(o.x.category)}</li>`).join('')}</ul></div>`;$('similar-box').classList.remove('hidden')}else $('similar-box').classList.add('hidden'); }
function renderCategorySuggestions(){const q=$('tool-category').value.toLowerCase().trim();const list=categories().filter(c=>!q||c.toLowerCase().includes(q)).sort((a,b)=>{const ac=a.toLowerCase().startsWith(q),bc=b.toLowerCase().startsWith(q);return Number(bc)-Number(ac)||a.localeCompare(b)}).slice(0,8);const html=list.map(c=>`<button type="button" class="suggestion" data-use-category="${esc(c)}"><span>▣ ${esc(c)}</span><small>${state.tools.filter(x=>x.category===c).length} tools</small></button>`).join('');const create=q&&!categories().some(c=>c.toLowerCase()===q)?`<button type="button" class="suggestion" data-create-category="${esc($('tool-category').value.trim())}"><span>＋ Create New Category</span><small>${esc($('tool-category').value.trim())}</small></button>`:'';$('category-suggestions').innerHTML=html+create;$('category-suggestions').classList.toggle('hidden',!(html||create));document.querySelectorAll('[data-use-category]').forEach(b=>b.onclick=()=>{$('tool-category').value=b.dataset.useCategory;$('category-suggestions').classList.add('hidden');showUrlWarnings()});document.querySelectorAll('[data-create-category]').forEach(b=>b.onclick=()=>{$('tool-category').value=b.dataset.createCategory;$('category-suggestions').classList.add('hidden');toast('New category will be created when saved')});}
function renderTagSuggestions(){const q=tokenise($('tool-name').value+' '+$('tool-url').value+' '+$('tool-category').value);const freq={};state.tools.flatMap(x=>x.tags||[]).forEach(t=>freq[t]=(freq[t]||0)+1);const candidates=unique([...q,...Object.keys(freq).sort((a,b)=>freq[b]-freq[a])]).filter(t=>t.length>2&&!($('tool-tags').value||'').toLowerCase().split(',').map(x=>x.trim()).includes(t.toLowerCase())).slice(0,8);$('tag-suggestions').innerHTML=candidates.map(t=>`<button type="button" class="chip" data-add-tag="${esc(t)}">＋${esc(t)}</button>`).join('');document.querySelectorAll('[data-add-tag]').forEach(b=>b.onclick=()=>{$('tool-tags').value=unique([...$('tool-tags').value.split(',').map(x=>x.trim()).filter(Boolean),b.dataset.addTag]).join(', ');renderTagSuggestions()});}
$('tool-form').onsubmit=async e=>{e.preventDefault();const id=$('tool-id').value||uid();const old=state.tools.find(x=>x.id===id);let url=$('tool-url').value.trim();if(url&&!/^https?:\/\//i.test(url))url='https://'+url;if(!/^https?:\/\//i.test(url))return toast('Use a valid http/https URL');const dup=duplicateForUrl(url,id);if(dup)return toast(`Already exists: ${dup.name}`);const item=normalizeTool({id,name:$('tool-name').value.trim(),url,category:$('tool-category').value.trim()||'Uncategorized',type:$('tool-type').value,tags:$('tool-tags').value.split(',').map(x=>x.trim()).filter(Boolean),description:$('tool-description').value.trim(),notes:$('tool-notes').value.trim(),favorite:old?.favorite||false,lastUsed:old?.lastUsed||0,addedAt:old?.addedAt||Date.now(),lastModified:Date.now()},'local');enrichTool(item);if(old)Object.assign(old,item);else state.tools.push(item);state.selected.delete(id);await save();closeModal();render();toast(old?'Tool updated':'Tool added');};
$('delete-tool').onclick=async()=>{const id=$('tool-id').value;if(!id)return;const x=state.tools.find(t=>t.id===id);if(!confirm(`Delete "${x?.name||'this tool'}"?`))return;state.tools=state.tools.filter(x=>x.id!==id);await save();closeModal();render();toast('Tool deleted')};

function setActiveNav(view){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));}
async function moveTools(ids){const target=prompt(`Move ${ids.length} tool${ids.length===1?'':'s'} to category.\n\nExisting: ${categories().join(', ')}`);if(!target?.trim())return;const cat=target.trim();state.tools.filter(x=>ids.includes(x.id)).forEach(x=>{x.category=cat;x.lastModified=Date.now()});state.selected.clear();await save();render();toast(`Moved ${ids.length} tool${ids.length===1?'':'s'} to ${cat}`)}
function selectedTools(){return state.tools.filter(x=>state.selected.has(x.id));}

$('open-add').onclick=()=>openModal();$('sidebar-add').onclick=()=>openModal();$('close-modal').onclick=closeModal;$('close-details').onclick=closeDetails;$('cancel-modal').onclick=closeModal;$('settings-btn').onclick=async()=>{$('settings-modal').classList.remove('hidden');updateSyncStatus()};$('close-settings').onclick=()=>{$('settings-modal').classList.add('hidden')};
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));
$('search').oninput=e=>{state.query=e.target.value;render()};$('type-filter').onchange=e=>{state.type=e.target.value;render()};$('sort').onchange=e=>{state.sort=e.target.value;render()};$('clear-search').onclick=()=>{state.query='';state.type='';state.category='';state.view='all';$('search').value='';$('type-filter').value='';setActiveNav('all');render()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.category='';setActiveNav(state.view);render()});
$('theme').onchange=async e=>{state.settings.theme=e.target.value;await save();applySettings()};$('density').onchange=async e=>{state.settings.density=e.target.value;await save();applySettings()};
$('tool-category').oninput=()=>{renderCategorySuggestions();showUrlWarnings()};$('tool-category').onfocus=renderCategorySuggestions;$('tool-name').oninput=()=>{renderTagSuggestions();showUrlWarnings()};$('tool-url').oninput=()=>{showUrlWarnings();renderTagSuggestions()};document.addEventListener('click',e=>{if(!e.target.closest('.field-wrap'))$('category-suggestions').classList.add('hidden')});

$('open-visible').onclick=async()=>{const arr=filtered();if(!arr.length)return toast('No visible tools to open');if(arr.length>15&&!confirm(`Open ${arr.length} tabs?`))return;for(const x of arr){let url=x.url;if(!/^https?:\/\//i.test(url))url='https://'+url;try{await chrome.tabs.create({url,active:false});x.lastUsed=Date.now()}catch{}}await save();render();toast(`Opened ${arr.length} tabs`)};
$('select-visible').onclick=()=>{filtered().forEach(x=>state.selected.add(x.id));render()};$('bulk-clear').onclick=()=>{state.selected.clear();render()};$('bulk-category').onclick=()=>moveTools([...state.selected]);$('bulk-tag').onclick=async()=>{const tag=prompt('Tag to add:');if(!tag?.trim())return;selectedTools().forEach(x=>x.tags=unique([...(x.tags||[]),tag.trim()]));await save();render();toast('Tag added')};$('bulk-favorite').onclick=async()=>{selectedTools().forEach(x=>x.favorite=true);await save();render();toast('Favorites updated')};$('bulk-export').onclick=()=>exportJSON(selectedTools(),'charlie-mj-selected-tools.json');$('bulk-delete').onclick=async()=>{if(!state.selected.size||!confirm(`Delete ${state.selected.size} selected tools?`))return;state.tools=state.tools.filter(x=>!state.selected.has(x.id));state.selected.clear();await save();render();toast('Selected tools deleted')};

function exportJSON(tools=state.tools,name='charlie-mj-tools.json'){download(name,JSON.stringify({version:4,app:'Charlie MJ Tool Archive',exportedAt:new Date().toISOString(),tools},null,2),'application/json');}
$('export-json').onclick=()=>exportJSON();
$('export-csv').onclick=()=>{const rows=[['Name','URL','Category','Type','Tags','Description','Notes','Favorite','Added','Last Used']];state.tools.forEach(x=>rows.push([x.name,x.url,x.category,x.type,(x.tags||[]).join('; '),x.description||'',x.notes||'',x.favorite?'Yes':'No',x.addedAt?new Date(x.addedAt).toISOString():'',x.lastUsed?new Date(x.lastUsed).toISOString():'']));download('charlie-mj-tools.csv',rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv');toast('CSV exported')};
function buildHtml(){const data=state.tools;const rows=data.map(x=>`<article class="tool"><h2>${esc(x.name)}</h2><p class="url"><a href="${esc(x.url)}">${esc(x.url)}</a></p><p><b>Category:</b> ${esc(x.category)} · <b>Type:</b> ${esc(x.type)}</p><p>${esc(x.description||'')}</p>${x.tags?.length?`<p><b>Tags:</b> ${x.tags.map(esc).join(', ')}</p>`:''}${x.notes?`<p><b>Notes:</b> ${esc(x.notes)}</p>`:''}<small>Favorite: ${x.favorite?'Yes':'No'} · Added: ${x.addedAt?new Date(x.addedAt).toLocaleString():'—'} · Last used: ${x.lastUsed?new Date(x.lastUsed).toLocaleString():'Never'}</small></article>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Charlie MJ Tool Archive</title><style>body{font-family:Inter,Segoe UI,Arial,sans-serif;margin:0;background:#071022;color:#eef3ff}header{padding:28px;background:linear-gradient(135deg,#15164a,#081d40);position:sticky;top:0}main{max-width:1100px;margin:auto;padding:22px}.tool{background:#101d38;border:1px solid #29446d;border-radius:14px;padding:16px;margin:12px 0}.tool h2{margin:0 0 7px}.url a{color:#72b8ff}.muted{color:#9fb0cc}input{padding:10px;width:100%;box-sizing:border-box;border-radius:8px;border:1px solid #385579;background:#081326;color:#fff}.cat{color:#9faeff}</style></head><body><header><h1>Charlie MJ Tool Archive</h1><p>${data.length} tools · exported ${new Date().toLocaleString()}</p><input id="q" placeholder="Search this offline archive..."></header><main id="list">${rows}</main><script>q.oninput=()=>{const v=q.value.toLowerCase();document.querySelectorAll('.tool').forEach(x=>x.style.display=x.innerText.toLowerCase().includes(v)?'block':'none')}</script></body></html>`;}
$('export-html').onclick=()=>{download('charlie-mj-tool-archive.html',buildHtml(),'text/html');toast('Detailed HTML exported')};

function download(name,text,type){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

async function prepareImport(incoming,label){const clean=[];const seen=new Set();for(const raw of incoming||[]){if(!raw?.url)continue;const x=normalizeTool(raw,'import');const k=normalizeUrl(x.url);if(!k||seen.has(k))continue;seen.add(k);clean.push(x)}const existingKeys=new Set(state.tools.map(x=>normalizeUrl(x.url)));const exact=clean.filter(x=>existingKeys.has(normalizeUrl(x.url)));const fresh=clean.filter(x=>!existingKeys.has(normalizeUrl(x.url)));const similar=fresh.filter(x=>state.tools.some(old=>{const a=unique(tokenise(old.name+' '+old.url));const b=unique(tokenise(x.name+' '+x.url));return a.filter(t=>b.includes(t)).length>=2;}));state.pendingImport={items:fresh,label};$('preview-summary').innerHTML=`<div class="health-grid"><div class="health-stat"><b>${clean.length}</b><span>Found</span></div><div class="health-stat"><b>${fresh.length}</b><span>New</span></div><div class="health-stat"><b>${exact.length}</b><span>Already exists</span></div></div>${similar.length?`<div class="warning-box">🔎 ${similar.length} new item${similar.length===1?'':'s'} look similar to existing tools. They are still importable.</div>`:''}`;$('preview-table').innerHTML=`<table class="preview-table"><thead><tr><th>Name</th><th>Category</th><th>URL</th><th>Status</th></tr></thead><tbody>${clean.slice(0,60).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.category)}</td><td>${esc(x.url)}</td><td>${existingKeys.has(normalizeUrl(x.url))?'<span class="mini-badge">Already exists</span>':'<span class="mini-badge">New</span>'}</td></tr>`).join('')}</tbody></table>`;$('confirm-preview').disabled=!fresh.length;$('confirm-preview').textContent=fresh.length?`Import ${fresh.length} New Tools`:'Nothing New';$('preview-modal').classList.remove('hidden');}
$('import-json').onclick=()=>$('json-file').click();$('json-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());const incoming=Array.isArray(data)?data:data.tools;if(!Array.isArray(incoming))throw Error('Invalid');await prepareImport(incoming,'JSON import')}catch{toast('Invalid JSON file')}e.target.value=''};
$('import-html').onclick=()=>$('html-file').click();$('html-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await prepareImport(parseBookmarks(await f.text()),'Chrome bookmarks')}catch{toast('Could not read bookmarks HTML')}e.target.value=''};
$('close-preview').onclick=$('cancel-preview').onclick=()=>{$('preview-modal').classList.add('hidden');state.pendingImport=null};$('confirm-preview').onclick=async()=>{if(!state.pendingImport)return;const incoming=state.pendingImport.items;state.tools=dedupeTools([...state.tools,...incoming]).tools;await save();$('preview-modal').classList.add('hidden');state.pendingImport=null;render();toast(`Imported ${incoming.length} new tools`)};
function parseBookmarks(html){const doc=new DOMParser().parseFromString(html,'text/html'),out=[];doc.querySelectorAll('a[href]').forEach(a=>{const url=a.getAttribute('href');if(!/^https?:/i.test(url))return;let p=a.parentElement,folder='Imported Bookmarks';while(p){const h=p.previousElementSibling;if(h&&h.tagName==='H3'){folder=h.textContent.trim();break}p=p.parentElement}out.push({name:a.textContent.trim()||url,url,category:folder,type:'Website',tags:[]})});return out;}

$('restore-defaults').onclick=async()=>{try{const r=await fetch('../data/default-tools.json',{cache:'no-store'}),d=await r.json(),incoming=Array.isArray(d)?d:d.tools;const before=state.tools.length;state.tools=dedupeTools([...state.tools,...incoming]).tools;await save();render();toast(`Bundled defaults: ${state.tools.length-before} new tools`)}catch{toast('Could not restore bundled library')}};
$('backup-json').onclick=()=>exportJSON(state.tools,'charlie-mj-tool-archive-backup.json');$('restore-backup').onclick=()=>{$('restore-file-modal').classList.remove('hidden');$('restore-json-file').value=''};$('close-restore-file').onclick=$('cancel-restore-file').onclick=()=>{$('restore-file-modal').classList.add('hidden')};$('confirm-restore-file').onclick=async()=>{const f=$('restore-json-file').files[0];if(!f)return toast('Choose a JSON backup first');try{const d=JSON.parse(await f.text()),incoming=Array.isArray(d)?d:d.tools;if(!Array.isArray(incoming))throw Error();state.tools=dedupeTools([...state.tools,...incoming]).tools;await save();$('restore-file-modal').classList.add('hidden');render();toast('Backup restored')}catch{toast('Invalid backup file')}};

async function updateSyncStatus(){try{const s=await chrome.runtime.sendMessage({type:'get-sync-state'});$('sync-status').innerHTML=s?.lastStatus==='success'?`<strong>✓ Connected</strong> · Last sync: ${s.lastSync?new Date(s.lastSync).toLocaleString():'—'} · GitHub tools: ${s.remoteCount||'—'} · Added last sync: ${s.added||0} · Enriched: ${s.enriched||0}`:`<strong>⚠ Sync status:</strong> ${esc(s?.lastError||'Waiting for first sync')}`;}catch{$('sync-status').textContent='Sync status unavailable';}}
$('sync-github').onclick=async()=>{const b=$('sync-github');b.disabled=true;b.textContent='↻ Syncing…';await syncGithub();await updateSyncStatus();b.disabled=false;b.textContent='↻ Sync from GitHub Now'};$('open-github').onclick=()=>chrome.tabs.create({url:'https://github.com/awsrmmustansarjavaid/charlie-mj-tool-archive/blob/main/data/default-tools.json'});

$('dedupe-library').onclick=async()=>{const r=dedupeTools(state.tools);state.tools=r.tools;state.selected.clear();await save();render();toast(r.removed?`Removed ${r.removed} duplicate record${r.removed===1?'':'s'}`:'No duplicate URLs found')};
function health(){const duplicates={};state.tools.forEach(x=>{const k=normalizeUrl(x.url);(duplicates[k]??=[]).push(x)});const dupGroups=Object.values(duplicates).filter(a=>a.length>1);const missingDesc=state.tools.filter(x=>!x.description.trim()).length,missingCat=state.tools.filter(x=>!x.category.trim()||x.category==='Uncategorized').length,invalid=state.tools.filter(x=>!/^https?:\/\//i.test(x.url)).length,never=state.tools.filter(x=>!x.lastUsed).length;return {dupGroups,missingDesc,missingCat,invalid,never}};
$('library-health').onclick=()=>{const h=health();$('health-grid').innerHTML=[['Tools',state.tools.length],['Categories',categories().length],['Duplicate groups',h.dupGroups.length],['Missing descriptions',h.missingDesc],['Missing categories',h.missingCat],['Invalid URLs',h.invalid],['Never used',h.never]].map(x=>`<div class="health-stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');$('health-details').innerHTML=h.dupGroups.length?`<div class="warning-box"><strong>Duplicate groups:</strong><ul class="similar-list">${h.dupGroups.slice(0,20).map(g=>`<li>${g.map(x=>esc(x.name)).join(' · ')}</li>`).join('')}</ul></div>`:'<div class="success-box">✓ No duplicate URL groups detected.</div>';$('health-modal').classList.remove('hidden')};$('close-health').onclick=()=>$('health-modal').classList.add('hidden');

function renderCategoriesManager(){ $('manager-list').innerHTML=categories().map(c=>`<div class="manager-row"><div><strong>${esc(c)}</strong><div class="meta">${state.tools.filter(x=>x.category===c).length} tools</div></div><div class="manager-actions"><button class="btn" data-rename-cat="${esc(c)}">Rename</button><button class="btn" data-merge-cat="${esc(c)}">Merge</button><button class="btn danger" data-delete-cat="${esc(c)}">Delete</button></div></div>`).join('');document.querySelectorAll('[data-rename-cat]').forEach(b=>b.onclick=async()=>{const old=b.dataset.renameCat,n=prompt(`Rename category "${old}" to:`,old);if(!n||n.trim()===old)return;state.tools.filter(x=>x.category===old).forEach(x=>x.category=n.trim());await save();renderCategoriesManager();render();toast('Category renamed')});document.querySelectorAll('[data-merge-cat]').forEach(b=>b.onclick=async()=>{const old=b.dataset.mergeCat,target=prompt(`Merge "${old}" into which category?`,categories().filter(c=>c!==old)[0]||'Uncategorized');if(!target||target===old)return;state.tools.filter(x=>x.category===old).forEach(x=>x.category=target.trim());await save();renderCategoriesManager();render();toast('Categories merged')});document.querySelectorAll('[data-delete-cat]').forEach(b=>b.onclick=async()=>{const c=b.dataset.deleteCat;if(!confirm(`Delete category "${c}"? Tools will move to Uncategorized.`))return;state.tools.filter(x=>x.category===c).forEach(x=>x.category='Uncategorized');await save();renderCategoriesManager();render();toast('Category deleted')});}
$('category-manager').onclick=()=>{$('category-modal').classList.remove('hidden');renderCategoriesManager()};$('close-category').onclick=()=>$('category-modal').classList.add('hidden');$('create-category').onclick=()=>{const c=$('new-category').value.trim();if(!c)return;if(categories().some(x=>x.toLowerCase()===c.toLowerCase()))return toast('Category already exists');$('new-category').value='';toast(`Category "${c}" is ready to use`);renderCategoriesManager()};

$('check-links').onclick=async()=>{const arr=state.tools; $('link-results').innerHTML=`<div class="sync-status">Checking ${arr.length} websites… This can take a while.</div>`;$('link-modal').classList.remove('hidden');const results=[];for(let i=0;i<arr.length;i++){const x=arr[i];let status='warn',label='Blocked/unknown';try{const r=await fetch(x.url,{method:'HEAD',redirect:'follow',cache:'no-store'});status=r.ok?'ok':r.status<500?'warn':'bad';label=r.ok?`HTTP ${r.status}`:`HTTP ${r.status}`}catch{try{const r=await fetch(x.url,{method:'GET',redirect:'follow',cache:'no-store'});status=r.ok?'ok':'warn';label=r.ok?`HTTP ${r.status}`:'Request blocked'}catch{status='warn';label='Browser blocked check'}}results.push({x,status,label});$('link-results').innerHTML=results.map(o=>`<div class="check-row"><span>${esc(o.x.name)}</span><small>${esc(hostname(o.x.url))}</small><span class="status ${o.status}">${o.status==='ok'?'✓':o.status==='bad'?'✕':'⚠'} ${esc(o.label)}</span></div>`).join('');}}
$('close-links').onclick=()=>$('link-modal').classList.add('hidden');

document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('search').focus()}if(e.key==='Escape'){closeModal();closeDetails();$('settings-modal').classList.add('hidden');$('preview-modal').classList.add('hidden');$('category-modal').classList.add('hidden');$('health-modal').classList.add('hidden');$('link-modal').classList.add('hidden');$('restore-file-modal').classList.add('hidden');closeCardMenus()}});
load();
